### ISSUE TITLE
Empty File 'utils/_init_.py'

### ISSUE THREAD

**Issue by MaaidahAfzaal** [mlaves/uncertainty-deep-image-prior#3]
I was just trying to look at your code and it appears that the file 'utils/_init_.py' is empty yet there are some functions that have been called from this file. Can you please help me out in this matter?

**Comment by mlaves** [comment]
An empty `__init__.py` is perfectly fine and the code should work as is.

https://docs.python.org/3/tutorial/modules.html#packages:
> The `__init__.py` files are required to make Python treat directories containing the file as packages. This prevents directories with a common name, such as string, unintentionally hiding valid modules that occur later on the module search path. In the simplest case, `__init__.py` can just be an empty file, but it can also execute initialization code for the package or set the `__all__` variable, described later.
